# Pre-Processing

## Importing necessary libraries

In [2]:
from numpy import expand_dims
from numpy import zeros
from numpy import ones
from numpy import vstack
from numpy.random import randn
from numpy.random import randint
from keras.datasets.mnist import load_data
from keras.optimizers import Adam
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Reshape
from keras.layers import Flatten
from keras.layers import Conv2D
from keras.layers import Conv2DTranspose
from keras.layers import LeakyReLU
from keras.layers import Dropout
from matplotlib import pyplot as plt
from IPython.display import clear_output

## Preparing Data

In [8]:
import os
from PIL import Image
import numpy as np

def sigmoid(x):
    return 1 / (1+np.exp(-x))

def inv_sigmoid(y):
    return np.log(y/(1-y))

%matplotlib inline

path = 'Abstract_gallery'
os.getcwd()
img_list = os.listdir(path)

def access_images(img_list,path,length):
    pixels = []
    imgs = []
    for i in range(length):
        img = Image.open(path+"\\"+img_list[i],'r')
        basewidth = 100
        img = img.resize((basewidth,basewidth),Image.ANTIALIAS)
        pix = np.array(img.getdata())
        pixels.append(pix.reshape(100,100,3))
        imgs.append(img)
        
    return np.array(pixels),imgs

def show_image(pix_list):
    array = np.array(pix_list.reshape(100,100,3), dtype = np.uint8)
    new_image = Image.fromarray(array)
    new_image.show()
    
pixels,imgs = access_images(img_list,path,1000)
pixels.shape

(1000, 100, 100, 3)

## Defining discriminator
This discriminator takes in the list of fake and real images as input and returns a single value between 0 and 1. 0 tends to real and 1 tends to fake.

In [9]:
def define_discriminator(in_shape = (100,100,3)):
    model = Sequential()
    model.add(Conv2D(64, (3,3), strides=(2, 2), padding='same', input_shape=in_shape))
    model.add(LeakyReLU(alpha=0.2))
    model.add(Dropout(0.4))
    model.add(Conv2D(64, (3,3), strides=(2, 2), padding='same'))
    model.add(LeakyReLU(alpha=0.2))
    model.add(Dropout(0.4))
    model.add(Flatten())
    model.add(Dense(1, activation='sigmoid'))
    opt = Adam(lr=0.0002, beta_1=0.5)
    model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy'])
    return model

## Defining generator

In [10]:
def define_generator(latent_dim):
    model = Sequential()
    n_nodes = 128 * 25 * 25
    model.add(Dense(n_nodes, input_dim=latent_dim))
    model.add(LeakyReLU(alpha=0.2))
    model.add(Reshape((25, 25, 128)))
    model.add(Conv2DTranspose(128, (4,4), strides=(2,2), padding='same'))
    model.add(LeakyReLU(alpha=0.2))
    model.add(Conv2DTranspose(128, (4,4), strides=(2,2), padding='same'))
    model.add(LeakyReLU(alpha=0.2))
    model.add(Conv2D(3, (7,7) , padding='same'))
    return model

## Defining GAN

In [11]:
def define_gan(g_model, d_model):
    d_model.trainable = False
    model = Sequential()
    model.add(g_model)
    model.add(d_model)
    opt = Adam(lr=0.0002, beta_1=0.5)
    model.compile(loss='binary_crossentropy', optimizer=opt)
    return model

## Generate Parts

In [13]:
def generate_real_samples(dataset, n_samples):
    ix = randint(0, dataset.shape[0], n_samples)
    X = dataset[ix]
    y = ones((n_samples, 1))
    return X, y
 
def generate_latent_points(latent_dim, n_samples):
    x_input = randn(latent_dim * n_samples)
    x_input = x_input.reshape(n_samples, latent_dim)
    return x_input

def generate_fake_samples(g_model, latent_dim, n_samples):
    x_input = generate_latent_points(latent_dim, n_samples)
    X = g_model.predict(x_input)
    y = zeros((n_samples, 1))
    return X, y

# Training

In [14]:
def train(g_model, d_model, gan_model, dataset, latent_dim, n_epochs=100, n_batch=10):
    bat_per_epo = int(dataset.shape[0] / n_batch)
    print(dataset.shape[0])
    half_batch = int(n_batch / 2)
    for i in range(n_epochs):
        for j in range(bat_per_epo):
            X_real, y_real = generate_real_samples(dataset, half_batch)
            X_fake, y_fake = generate_fake_samples(g_model, latent_dim, half_batch)
            X, y = vstack((X_real, X_fake)), vstack((y_real, y_fake))
            d_loss, _ = d_model.train_on_batch(X, y)
            X_gan = generate_latent_points(latent_dim, n_batch)
            y_gan = ones((n_batch, 1))
            g_loss = gan_model.train_on_batch(X_gan, y_gan)
            print('>%d, %d/%d, d=%.3f, g=%.3f' % (i+1, j+1, bat_per_epo, d_loss, g_loss))
        if (i+1) % 10 == 0:
            summarize_performance(i, g_model, d_model, dataset, latent_dim)
            clear_output()

## Performance metrics summarization

In [16]:
def summarize_performance(epoch, g_model, d_model, dataset, latent_dim, n_samples=100):
    X_real, y_real = generate_real_samples(dataset, n_samples)
    _, acc_real = d_model.evaluate(X_real, y_real, verbose=0)
    x_fake, y_fake = generate_fake_samples(g_model, latent_dim, n_samples)
    _, acc_fake = d_model.evaluate(x_fake, y_fake, verbose=0)
    print('>Accuracy real: %.0f%%, fake: %.0f%%' % (acc_real*100, acc_fake*100))
    filename = 'generator_model_%03d.h5' % (epoch + 1)
    g_model.save(filename)

## Starting the Training

In [17]:
latent_dim = 100
d_model = define_discriminator()
g_model = define_generator(latent_dim)
gan_model = define_gan(g_model, d_model)
print(pixels.shape)
train(g_model, d_model, gan_model, np.array(pixels), latent_dim)
print(pixels)

[[[[239 238 236]
   [243 242 240]
   [241 241 239]
   ...
   [239 237 238]
   [239 237 238]
   [239 237 238]]

  [[238 236 234]
   [220 218 216]
   [221 219 218]
   ...
   [161 160 160]
   [175 174 175]
   [239 237 238]]

  [[225 222 220]
   [143 140 139]
   [161 159 157]
   ...
   [160 160 160]
   [176 176 177]
   [240 238 240]]

  ...

  [[247 246 244]
   [219 218 216]
   [140 139 137]
   ...
   [139 139 139]
   [161 161 161]
   [211 210 209]]

  [[248 247 245]
   [214 213 211]
   [109 108 106]
   ...
   [163 163 163]
   [169 169 169]
   [209 208 207]]

  [[243 243 241]
   [232 231 229]
   [190 189 187]
   ...
   [244 244 244]
   [240 240 240]
   [239 237 238]]]


 [[[248 248 246]
   [247 247 245]
   [249 249 247]
   ...
   [255 255 255]
   [255 255 255]
   [249 249 246]]

  [[248 248 246]
   [248 248 246]
   [237 237 235]
   ...
   [107 105 103]
   [170 168 167]
   [253 253 252]]

  [[246 245 244]
   [255 255 255]
   [146 144 139]
   ...
   [ 22  21  19]
   [100  98  96]
   [255 255

# Inference (or actual usage)

In [31]:
from keras.models import load_model
from numpy.random import randn
from matplotlib import pyplot

def generate_latent_points(latent_dim, n_samples):
    x_input = randn(latent_dim * n_samples)
    x_input = x_input.reshape(n_samples, latent_dim)
    return x_input

model = g_model
latent_points = generate_latent_points(100,1)
X = model.predict(latent_points)

array = np.array(X.reshape(100,100,3), dtype=np.uint8)
new_image = Image.fromarray(array)
new_image = new_image.resize((400,400))
new_image.show()
new_image.save("output.jpg")